name: Test ECR Access

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: flask-tp-app

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Install Amazon ECR Docker Credential Helper
        run: |
          curl -Lo docker-credential-ecr-login \
            https://github.com/awslabs/amazon-ecr-credential-helper/releases/download/v0.9.1/docker-credential-ecr-login-linux-amd64
          chmod +x docker-credential-ecr-login
          sudo mv docker-credential-ecr-login /usr/local/bin/

      - name: Configure Docker to use ECR credential helper
        run: |
          mkdir -p ~/.docker
          cat <<EOF > ~/.docker/config.json
          {
            "credsStore": "ecr-login"
          }
          EOF

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Verify ECR repo exists
        run: |
          aws ecr describe-repositories \
            --repository-names "$ECR_REPOSITORY" \
            --output table

      - name: Docker login to ECR
        run: |
          aws ecr get-login-password \
            --region "$AWS_REGION" | \
          docker login \
            --username AWS \
            --password-stdin "${{ steps.login-ecr.outputs.registry }}"